# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

Mendoza Hernandez Carlos Emiliano

In [1]:
import numpy as np
np.set_printoptions(legacy='1.13')

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))

[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [2]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

### **Ejercicio 2-  Suma de elementos:**
Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [3]:
np.sum(np.array([1, 2, 3, 4, 5]))

15

### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [4]:
array = np.array([10, 20, 30, 40, 50])
array.max(), array.min()

(50, 10)

### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [5]:
array = np.array([10, 20, 30, 40, 50])
array.max(), array.min()

(50, 10)

### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [6]:
np.random.random((1, 5))

array([[ 0.15512711,  0.41067524,  0.18178319,  0.53329422,  0.74703457]])

### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [7]:
np.array([1, 2, 3, 4, 5]).mean()

3.0

### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [8]:
A = np.array([1,2,3])
B = np.array([4,5,6])
np.concatenate((A, B))

array([1, 2, 3, 4, 5, 6])

### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [9]:
np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [10]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
A * B

array([ 4, 10, 18])

### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [11]:
np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [12]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])
np.partition(arr, 2)[2]

3

## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = ((retorno - inversión) / inversión) * 100

In [13]:
# Solucion del ROIROIROIROIORIORI
inversiones = np.array([1000, 1500, 2000])
retornos = np.array([1200, 1650, 1800])
roi = ((retornos - inversiones) / inversiones) * 100
roi

array([ 20.,  10., -10.])

### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [14]:
precios_usd = np.array([250, 320, 150, 500, 210])
precios_min_max_norm = (precios_usd - precios_usd.min()) / (precios_usd.max() - precios_usd.min())
precios_min_max_norm

array([ 0.28571429,  0.48571429,  0.        ,  1.        ,  0.17142857])

### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [15]:
ventas_diarias = np.array([1200, 0, 750, 2400, 0, 1800])
ventas_diarias[ventas_diarias == 0] = ventas_diarias.mean()
ventas_diarias

array([1200, 1025,  750, 2400, 1025, 1800])

### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [16]:
presion_arterial = np.array([120, 135, 140, 118, 150, 130, 160, 125, 142, 128])
media_pa = presion_arterial.mean()
desviacion_pa = presion_arterial.std()
pa_fuera_rango = presion_arterial[(presion_arterial < 90) | (presion_arterial > 140)]
print(media_pa)
print(desviacion_pa)
print(pa_fuera_rango)

134.8
12.694880858
[150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [17]:
pib_en_millones_usd = np.array([500, 320, 700, 450])
pob_en_millones = np.array([10, 8, 12, 9])
pib_per_capita = pib_en_millones_usd / pob_en_millones
mejor_pais = np.argmax(pib_per_capita)
print(pib_per_capita)
print(mejor_pais)

[ 50.          40.          58.33333333  50.        ]
2


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [18]:
drops = np.array([0, 1, 2, 3])
probas = np.array([0.50, 0.30, 0.15, 0.05])

num_drops = 100
drops_simulados = np.random.choice(drops, size=num_drops, p=probas)

artefactos_obtenidos = np.sum(drops_simulados == 3)
print(f"Artefactos obtenidos: {artefactos_obtenidos}")

Artefactos obtenidos: 3
